
package vistaFutoshiki;

import controladorFutoshiki.ControladorFutoshiki;
import modeloFutoshiki.*;

import modeloFutoshiki.Configuracion; //por los datos
import modeloFutoshiki.Jugador;
import modeloFutoshiki.Partida;
import modeloFutoshiki.PartidasFutoshiki;
import modeloFutoshiki.Top10;
import static vistaFutoshiki.GUIFutoshiki.configFutoshiki;




//documentar awt
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

//Documentar en PDF Timer
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.SwingUtilities;

//documentar awt
import javax.swing.*;

/**
 *
 * @author Kendall Ariel Rojas Cartin
 */

public class GUIJugar extends javax.swing.JFrame {
    
    Configuracion configJuego = configFutoshiki;
    Timer timerGlobal = new Timer(); //para guardar el timer actual
    private int horaGlobal = 0;
    private int minutoGlobal = 0;
    private int segundosGlobal = 0;
    boolean borrarGlobal = false;
    
    private int numeroElegido = 0;
    
    String errorString; //columna, fila, mayor, menor
    
    int[][] cuadriculaJuego;
    int[][] cuadriculaEnJuego;
    JButton[][] cuadriculaBotones;
    
    public GUIJugar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        numerosPanel = new javax.swing.JPanel();
        numero1Button = new javax.swing.JButton();
        numero2Button = new javax.swing.JButton();
        numero3Button = new javax.swing.JButton();
        numero4Button = new javax.swing.JButton();
        numero5Button = new javax.swing.JButton();
        numero6Button = new javax.swing.JButton();
        numero7Button = new javax.swing.JButton();
        numero8Button = new javax.swing.JButton();
        numero9Button = new javax.swing.JButton();
        numero10Button = new javax.swing.JButton();
        nivelLabel = new javax.swing.JLabel();
        nombreJugadorPanel = new javax.swing.JPanel();
        nombreJugadorLabel = new javax.swing.JLabel();
        nombreJugadorField = new javax.swing.JTextField();
        juegoPanel = new javax.swing.JPanel();
        guardarJuegoButton = new javax.swing.JButton();
        borrarJuegoButton = new javax.swing.JButton();
        borrarJugadaButton = new javax.swing.JButton();
        rehacerJugadaButton = new javax.swing.JButton();
        terminarJuegoButton = new javax.swing.JButton();
        cargarJuegoButton = new javax.swing.JButton();
        relojPanel = new javax.swing.JPanel();
        tiempoSegundosLabel = new javax.swing.JLabel();
        segundosLabel = new javax.swing.JLabel();
        minutosLabel = new javax.swing.JLabel();
        horasLabel = new javax.swing.JLabel();
        tiempoHorasLabel = new javax.swing.JLabel();
        tiempoMinutosLabel = new javax.swing.JLabel();
        iniciarJuegoButton = new javax.swing.JButton();
        anuncioLabel = new javax.swing.JLabel();
        borrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        fondoPanel.setPreferredSize(new java.awt.Dimension(1000, 900));
        fondoPanel.setLayout(null);

        tituloPanel.setBackground(new java.awt.Color(204, 0, 51));

        tituloLabel.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("FUTOSHIKI");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(49, 49, 49))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoPanel.add(tituloPanel);
        tituloPanel.setBounds(370, 10, 239, 43);

        numerosPanel.setBackground(new java.awt.Color(255, 255, 255));
        numerosPanel.setLayout(null);

        numero1Button.setBackground(new java.awt.Color(255, 255, 255));
        numero1Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero1Button.setForeground(new java.awt.Color(0, 0, 0));
        numero1Button.setText("1");
        numero1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero1Button);
        numero1Button.setBounds(0, 0, 72, 51);

        numero2Button.setBackground(new java.awt.Color(255, 255, 255));
        numero2Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero2Button.setForeground(new java.awt.Color(0, 0, 0));
        numero2Button.setText("2");
        numero2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero2Button);
        numero2Button.setBounds(0, 57, 72, 49);

        numero3Button.setBackground(new java.awt.Color(255, 255, 255));
        numero3Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero3Button.setForeground(new java.awt.Color(0, 0, 0));
        numero3Button.setText("3");
        numero3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero3Button);
        numero3Button.setBounds(0, 112, 72, 50);

        numero4Button.setBackground(new java.awt.Color(255, 255, 255));
        numero4Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero4Button.setForeground(new java.awt.Color(0, 0, 0));
        numero4Button.setText("4");
        numero4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero4ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero4Button);
        numero4Button.setBounds(0, 168, 72, 47);

        numero5Button.setBackground(new java.awt.Color(255, 255, 255));
        numero5Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero5Button.setForeground(new java.awt.Color(0, 0, 0));
        numero5Button.setText("5");
        numero5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero5ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero5Button);
        numero5Button.setBounds(0, 221, 72, 50);

        numero6Button.setBackground(new java.awt.Color(255, 255, 255));
        numero6Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero6Button.setForeground(new java.awt.Color(0, 0, 0));
        numero6Button.setText("6");
        numero6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero6Button);
        numero6Button.setBounds(0, 277, 72, 50);

        numero7Button.setBackground(new java.awt.Color(255, 255, 255));
        numero7Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero7Button.setForeground(new java.awt.Color(0, 0, 0));
        numero7Button.setText("7");
        numero7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero7Button);
        numero7Button.setBounds(0, 333, 72, 50);

        numero8Button.setBackground(new java.awt.Color(255, 255, 255));
        numero8Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero8Button.setForeground(new java.awt.Color(0, 0, 0));
        numero8Button.setText("8");
        numero8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero8Button);
        numero8Button.setBounds(0, 393, 72, 50);

        numero9Button.setBackground(new java.awt.Color(255, 255, 255));
        numero9Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero9Button.setForeground(new java.awt.Color(0, 0, 0));
        numero9Button.setText("9");
        numero9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero9ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero9Button);
        numero9Button.setBounds(0, 449, 72, 50);

        numero10Button.setBackground(new java.awt.Color(255, 255, 255));
        numero10Button.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        numero10Button.setForeground(new java.awt.Color(0, 0, 0));
        numero10Button.setText("10");
        numero10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero10ButtonActionPerformed(evt);
            }
        });
        numerosPanel.add(numero10Button);
        numero10Button.setBounds(0, 505, 72, 50);

        fondoPanel.add(numerosPanel);
        numerosPanel.setBounds(1000, 110, 80, 570);

        nivelLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nivelLabel.setForeground(new java.awt.Color(0, 0, 0));
        nivelLabel.setText("Nivel: ");
        fondoPanel.add(nivelLabel);
        nivelLabel.setBounds(360, 60, 239, 18);

        nombreJugadorPanel.setBackground(new java.awt.Color(255, 255, 255));

        nombreJugadorLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nombreJugadorLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreJugadorLabel.setText("Nombre del jugador: ");

        nombreJugadorField.setEditable(false);
        nombreJugadorField.setBackground(new java.awt.Color(255, 255, 255));
        nombreJugadorField.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nombreJugadorField.setForeground(new java.awt.Color(0, 0, 0));

        juegoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout juegoPanelLayout = new javax.swing.GroupLayout(juegoPanel);
        juegoPanel.setLayout(juegoPanelLayout);
        juegoPanelLayout.setHorizontalGroup(
            juegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        juegoPanelLayout.setVerticalGroup(
            juegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout nombreJugadorPanelLayout = new javax.swing.GroupLayout(nombreJugadorPanel);
        nombreJugadorPanel.setLayout(nombreJugadorPanelLayout);
        nombreJugadorPanelLayout.setHorizontalGroup(
            nombreJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nombreJugadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nombreJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nombreJugadorPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(juegoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nombreJugadorPanelLayout.createSequentialGroup()
                        .addComponent(nombreJugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJugadorField, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nombreJugadorPanelLayout.setVerticalGroup(
            nombreJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nombreJugadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nombreJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugadorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(juegoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoPanel.add(nombreJugadorPanel);
        nombreJugadorPanel.setBounds(188, 85, 759, 593);

        guardarJuegoButton.setBackground(new java.awt.Color(0, 153, 0));
        guardarJuegoButton.setFont(new java.awt.Font("Sitka Text", 1, 13)); // NOI18N
        guardarJuegoButton.setForeground(new java.awt.Color(0, 0, 0));
        guardarJuegoButton.setText("Guardar Juego");
        fondoPanel.add(guardarJuegoButton);
        guardarJuegoButton.setBounds(930, 700, 121, 57);

        borrarJuegoButton.setBackground(new java.awt.Color(51, 204, 255));
        borrarJuegoButton.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        borrarJuegoButton.setForeground(new java.awt.Color(0, 0, 0));
        borrarJuegoButton.setText("Borrar Juego");
        fondoPanel.add(borrarJuegoButton);
        borrarJuegoButton.setBounds(780, 700, 139, 57);

        borrarJugadaButton.setBackground(new java.awt.Color(0, 204, 204));
        borrarJugadaButton.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        borrarJugadaButton.setForeground(new java.awt.Color(0, 0, 0));
        borrarJugadaButton.setText("Borrar Jugada");
        fondoPanel.add(borrarJugadaButton);
        borrarJugadaButton.setBounds(630, 700, 139, 57);

        rehacerJugadaButton.setBackground(new java.awt.Color(255, 204, 153));
        rehacerJugadaButton.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        rehacerJugadaButton.setForeground(new java.awt.Color(0, 0, 0));
        rehacerJugadaButton.setText("Rehacer Jugada");
        fondoPanel.add(rehacerJugadaButton);
        rehacerJugadaButton.setBounds(630, 770, 139, 59);

        terminarJuegoButton.setBackground(new java.awt.Color(255, 255, 153));
        terminarJuegoButton.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        terminarJuegoButton.setForeground(new java.awt.Color(0, 0, 0));
        terminarJuegoButton.setText("Terminar Juego");
        terminarJuegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarJuegoButtonActionPerformed(evt);
            }
        });
        fondoPanel.add(terminarJuegoButton);
        terminarJuegoButton.setBounds(780, 770, 139, 59);

        cargarJuegoButton.setBackground(new java.awt.Color(204, 102, 0));
        cargarJuegoButton.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        cargarJuegoButton.setForeground(new java.awt.Color(0, 0, 0));
        cargarJuegoButton.setText("Cargar Juego");
        fondoPanel.add(cargarJuegoButton);
        cargarJuegoButton.setBounds(930, 770, 120, 59);

        relojPanel.setBackground(new java.awt.Color(255, 255, 255));

        tiempoSegundosLabel.setBackground(new java.awt.Color(255, 255, 255));
        tiempoSegundosLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tiempoSegundosLabel.setForeground(new java.awt.Color(0, 0, 0));
        tiempoSegundosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoSegundosLabel.setText("00");
        tiempoSegundosLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        segundosLabel.setBackground(new java.awt.Color(255, 255, 255));
        segundosLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        segundosLabel.setForeground(new java.awt.Color(0, 0, 0));
        segundosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segundosLabel.setText("Segundos");
        segundosLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        minutosLabel.setBackground(new java.awt.Color(255, 255, 255));
        minutosLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        minutosLabel.setForeground(new java.awt.Color(0, 0, 0));
        minutosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minutosLabel.setText("Minutos");
        minutosLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        horasLabel.setBackground(new java.awt.Color(255, 255, 255));
        horasLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        horasLabel.setForeground(new java.awt.Color(0, 0, 0));
        horasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horasLabel.setText("Horas");
        horasLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tiempoHorasLabel.setBackground(new java.awt.Color(255, 255, 255));
        tiempoHorasLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tiempoHorasLabel.setForeground(new java.awt.Color(0, 0, 0));
        tiempoHorasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoHorasLabel.setText("00");
        tiempoHorasLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tiempoMinutosLabel.setBackground(new java.awt.Color(255, 255, 255));
        tiempoMinutosLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tiempoMinutosLabel.setForeground(new java.awt.Color(0, 0, 0));
        tiempoMinutosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoMinutosLabel.setText("00");
        tiempoMinutosLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout relojPanelLayout = new javax.swing.GroupLayout(relojPanel);
        relojPanel.setLayout(relojPanelLayout);
        relojPanelLayout.setHorizontalGroup(
            relojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relojPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(relojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, relojPanelLayout.createSequentialGroup()
                        .addComponent(horasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(segundosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, relojPanelLayout.createSequentialGroup()
                        .addComponent(tiempoHorasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoMinutosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoSegundosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        relojPanelLayout.setVerticalGroup(
            relojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relojPanelLayout.createSequentialGroup()
                .addGroup(relojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(relojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tiempoMinutosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(tiempoHorasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addComponent(tiempoSegundosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fondoPanel.add(relojPanel);
        relojPanel.setBounds(220, 700, 393, 147);

        iniciarJuegoButton.setBackground(new java.awt.Color(255, 0, 51));
        iniciarJuegoButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        iniciarJuegoButton.setForeground(new java.awt.Color(0, 0, 0));
        iniciarJuegoButton.setText("Iniciar Juego");
        iniciarJuegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJuegoButtonActionPerformed(evt);
            }
        });
        fondoPanel.add(iniciarJuegoButton);
        iniciarJuegoButton.setBounds(70, 740, 117, 62);

        anuncioLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        anuncioLabel.setForeground(new java.awt.Color(0, 0, 0));
        fondoPanel.add(anuncioLabel);
        anuncioLabel.setBounds(620, 10, 350, 50);

        borrarBoton.setBackground(new java.awt.Color(255, 255, 255));
        borrarBoton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        borrarBoton.setForeground(new java.awt.Color(0, 0, 0));
        borrarBoton.setText("Borrar");
        borrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBotonActionPerformed(evt);
            }
        });
        fondoPanel.add(borrarBoton);
        borrarBoton.setBounds(1000, 50, 75, 50);

        getContentPane().add(fondoPanel);
        fondoPanel.setBounds(0, 0, 1100, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Verifica desigualdades
     * @param partida la partida
     * @param cuadricula la cuadricula de la partida
     **/
    
    public void verificarDesigualdad(Partida partida, int[][] cuadricula) {
        
        Map<String, int[]> desigualdades = partida.getDesigualdades();
        for (Map.Entry<String, int[]> entry : desigualdades.entrySet()) {
            
            String desigualdad = entry.getKey();
            int[] posicion = entry.getValue();

            int fila = posicion[0];
            int columna = posicion[1];
            int numActual = cuadricula[fila][columna];
            
            switch (desigualdad) {
                case "maf":
                    if (columna + 1 < cuadricula[fila].length) {
                        int numSiguiente = cuadricula[fila][columna + 1];
                        if (!(numActual > numSiguiente) && (numActual != 0 && numSiguiente!=0)) {
                            cuadriculaBotones[fila][columna].setForeground(Color.RED);
                            System.out.println(desigualdad);
                        }
                        else if ((numActual > numSiguiente) && (numActual != 0 && numSiguiente!=0)){
                            cuadriculaBotones[fila][columna].setForeground(new Color(0,100,0));
                        }
                    }   break;
                case "mef":
                    if (columna + 1 < cuadricula[fila].length) {
                        int numSiguiente = cuadricula[fila][columna + 1];
                        
                        if (!(numActual < numSiguiente) && (numActual != 0 && numSiguiente!=0)) {
                            cuadriculaBotones[fila][columna].setForeground(Color.RED);
                            System.out.println(desigualdad);
                        }
                        else if ((numActual < numSiguiente) && (numActual != 0 && numSiguiente!=0)){
                            cuadriculaBotones[fila][columna].setForeground(new Color(0,100,0));
                        }
                    }   break;
                case "mac":
                    if (fila + 1 < cuadricula.length) {
                        
                        int numSiguiente = cuadricula[fila + 1][columna];
                        if (!(numActual > numSiguiente) && (numActual != 0 && numSiguiente!=0)) {
                            cuadriculaBotones[fila][columna].setForeground(Color.RED);
                            System.out.println(desigualdad);
                        }
                        else if ((numActual > numSiguiente) && (numActual != 0 && numSiguiente!=0)){
                            cuadriculaBotones[fila][columna].setForeground(new Color(0,100,0));
                        }
                    }   break;
                case "mec":
                    if (fila + 1 < cuadricula.length) {
                        
                        int numSiguiente = cuadricula[fila + 1][columna];
                        if (!(numActual < numSiguiente) && (numActual != 0 && numSiguiente!=0)) {
                            cuadriculaBotones[fila][columna].setForeground(Color.RED);
                            System.out.println( desigualdad);
                        }
                        else if ((numActual < numSiguiente) && (numActual != 0 && numSiguiente!=0)){
                            cuadriculaBotones[fila][columna].setForeground(new Color(0,100,0));
                        }
                    }   break;
                default: //ninguno por si acaso fuera ""
                    break;
            }
        }
    }

    /**
     * La Alerta al finalizar el juego
     **/
    
    public void alertaFinalizar(){
        String mensaje;
        for (int filaNum = 0; filaNum < cuadriculaEnJuego.length; filaNum++) {
            for (int columnaNum = 0; columnaNum < cuadriculaEnJuego[filaNum].length; columnaNum++) {
                    if (cuadriculaEnJuego[filaNum][columnaNum] != cuadriculaJuego[filaNum][columnaNum]) {
                        System.out.println("Aun no termina");
                        return;
                    }
                }
        }
        
        mensaje = ("Finalizado!");
        cancelarTimer(timerGlobal);
        
        

        JTextArea areaTexto = new JTextArea();
        areaTexto.setEditable(false);
        areaTexto.setText("FINALIZADO!" +"\n" + " ¡EXCELENTE! JUEGO TERMINADO CON ÉXITO.");
        areaTexto.setFont(new Font("Sitka Text",Font.BOLD,14));
        areaTexto.setForeground(new Color(0,100,0));

         
        //ventana para mostrar la informacion
        JDialog ventanaInfo = new JDialog();
        ventanaInfo.setTitle("Finalizado!");
        ventanaInfo.setModal(true); // lo pone en modal lo que hace que no se pueda hacer nada hasta cerrar y asi que el jugador vea
        ventanaInfo.setBounds(500, 500, 500, 200); // x y ancho y altura
        
        ventanaInfo.add(areaTexto);
        ventanaInfo.setVisible(true);
        if (timerGlobal != null){
            cancelarTimer(timerGlobal);
            top10();
        }
        if (iniciarJuegoButton.isVisible()==false){
            iniciarJuegoButton.setVisible(true);
        
        }
        
        
        
        
    }
    
    /**
     * Envia al controlador para generar el Top10 y guardarlo
     **/
    
    public void top10(){
        System.out.println("Top 10");
        String jugador = nombreJugadorField.getText();
        int hora = horaGlobal;
        int minutos = minutoGlobal;
        int segundos = segundosGlobal;
        String nivel = configFutoshiki.getNivel();
        
        ControladorFutoshiki controlador = new ControladorFutoshiki();
        
        controlador.agregarAlTop10(jugador, hora, minutos, segundos, nivel);

        
        horaGlobal = 0;
        minutoGlobal = 0;
        segundosGlobal = 0;
        
    }
        
    /**
     * Alerta error
     * @param mensaje el mensaje del error dependiendo de que tipo
     **/
    
    public void alertaMensaje(String mensaje){
        System.out.println("Alerta");

        String infoAlerta = "";
        
        switch (mensaje) {
            case "columna":
                infoAlerta = "JUGADA NO ES VÁLIDA PORQUE EL ELEMENTO YA ESTÁ EN LA \n" +  "COLUMNA ";
                                                                                   
                break;
            case "fila":
                infoAlerta = "JUGADA NO ES VÁLIDA PORQUE EL ELEMENTO YA ESTÁ EN LA FILA";
                break;
            case "mayor":
                infoAlerta = "JUGADA NO ES VÁLIDA PORQUE NO CUMPLE CON LA RESTRICCIÓN \n" + "DE MAYOR";
                break;
            case "menor":
                infoAlerta = "JUGADA NO ES VÁLIDA PORQUE NO CUMPLE CON LA RESTRICCIÓN \n" + "DE MENOR ";
                break;
        }
        
        
         JTextArea areaTexto = new JTextArea();
         areaTexto.setEditable(false);
         areaTexto.setText("Alerta" +"\n" + infoAlerta);
         areaTexto.setFont(new Font("Sitka Text",Font.BOLD,14));
         areaTexto.setForeground(Color.RED);
         
        //ventana para mostrar la informacion
        JDialog ventanaInfo = new JDialog();
        ventanaInfo.setTitle("Alerta");
        ventanaInfo.setModal(true); // lo pone en modal lo que hace que no se pueda hacer nada hasta cerrar y asi que el jugador vea
        ventanaInfo.setBounds(500, 500, 500, 300); // x y ancho y altura
        
        ventanaInfo.add(areaTexto);
        ventanaInfo.setVisible(true);
    }
    
    /**
     * Crea la cuadricula que esta en juego actualmente
     * @param filas filas 
     * @param columnas columnas
     * @return cuadricula
     **/
    
    public int[][] crearCuadriculaEnJuego(int filas, int columnas){
        int[][] cuadricula = new int[filas][columnas];

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                cuadricula[i][j] = 0;
            }
        }
        return cuadricula;
    }
    
    /**
     * Crea la cuadricula de botones del juego
     * @param filas filas
     * @param columnas columnas
     * @return Cuadricula de JButton
     **/
    
    public JButton[][] crearCuadriculaBotones(int filas, int columnas){
        JButton[][] cuadricula = new JButton[filas][columnas];

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                cuadricula[i][j] = new JButton();
            }
        }
        return cuadricula;
    }
    
    /**
     * Limpia los botones del juego
     **/
    
    public void limpiarBotonesJuego(){
        for (Component componente : numerosPanel.getComponents()){
            JButton boton = (JButton) componente;
            boton.setBackground(Color.WHITE);
        }
    }
    
    /**
     * Convierte en Stringf la cuadricula dada
     * @param cuadricula cuadricula int[][]
     * @return String de la cuadricula
     **/
    
    public String cuadriculaToString(int[][] cuadricula) {
        String cuadriculaString = "";

        for (int i = 0; i < cuadricula.length; i++) {
            for (int j = 0; j < cuadricula[i].length; j++) {
                cuadriculaString += cuadricula[i][j];
                if (j < cuadricula[i].length - 1) {
                    cuadriculaString += " "; 
                }
            }
            cuadriculaString += "\n"; 
        }
        return cuadriculaString;
    }
    
    /**
     * Comprobar Filas y columnas de una cuadricula
     * @param cuadricula int[][] cuadricula
     * @return Si hay un error regresa el int[] x y de la posicion del error en caso de no encontrar null
     **/
    
    public int[] comprobarFilasColumnas(int[][] cuadricula) {
        int n = cuadricula.length; 
        
        for (int fila = 0; fila < n; fila++) { //filas
            for (int columna = 0; columna < n; columna++) {
                int valor = cuadricula[fila][columna];
                if (valor != 0) { 
                    for (int pComparar = columna + 1; pComparar < n; pComparar++) {
                        if (cuadricula[fila][pComparar] == valor) {
                            errorString = "fila"; //tipo de error
                            cuadriculaBotones[fila][pComparar].setForeground(Color.RED);
                            return new int[] {fila, pComparar}; //posicion del error
                        }
                        else if (cuadricula[fila][pComparar] != valor && cuadriculaBotones[fila][pComparar].getForeground() == Color.RED){
                            cuadriculaBotones[fila][pComparar].setForeground(new Color(0,100,0));
                        }
                    }
                }
            }
        }

        for (int columna = 0; columna < n; columna++) { //columnas
            for (int fila = 0; fila < n; fila++) {
                int valor = cuadricula[fila][columna];
                if (valor != 0) { 
                    for (int pComparar = fila + 1; pComparar < n; pComparar++) {
                        if (cuadricula[pComparar][columna] == valor) {
                            errorString = "columna"; //tipo de error
                            cuadriculaBotones[pComparar][columna].setForeground(Color.RED);
                            return new int[] {pComparar, columna};  //posicion del error
                        }
                        else if (cuadricula[pComparar][columna] != valor && cuadriculaBotones[pComparar][columna].getForeground() == Color.RED){
                            cuadriculaBotones[pComparar][columna].setForeground(new Color(0,100,0));
                        }
                    }
                }
            }
        }
        return null; 
    }
    
    /**
     * Genera la cuadricula con la partida y el tamano de la matriz
     * @param partida La partida en juego
     * @param cuadriculaTamano tamano de matriz en byte
     **/
    
    public void generarCuadricula(Partida partida, byte cuadriculaTamano) {
        JPanel panel = juegoPanel;
        panel.removeAll(); //reiniciar panel

        cuadriculaJuego = partida.getPartidaJuego();
        Map<String, int[]> desigualdades = partida.getDesigualdades();

        int filas = cuadriculaJuego.length;
        int columnas = cuadriculaJuego[0].length;

        cuadriculaEnJuego = crearCuadriculaEnJuego(filas, columnas);

        cuadriculaBotones = crearCuadriculaBotones(filas, columnas);
        
        GridLayout gridLayout = new GridLayout(filas * 2 - 1, columnas * 2 - 1); //son filas y columnas * 2 - 1 para sacar espacios entre numeros y poner las desigualdades
                                                                                        // y juntarlo con la matriz original es decir 3x3 seria 5x5 y asi
        panel.setLayout(gridLayout);

        int espacioHorizontal = Math.max(5, 40 / cuadriculaTamano); //para evitar que sean muy grandes y no entren en pantalla las matrices del juego se hacen calculos
        int espacioVertical = Math.max(5, 40 / cuadriculaTamano); //math max minimo maximo
        gridLayout.setHgap(espacioHorizontal); // hgap = gap horizontal
        gridLayout.setVgap(espacioVertical); // vgap = gap horizontal
        
        int botonTamano = Math.max(20, 180 / cuadriculaTamano); //evitar botones muy grandes

        for (int i = 0; i < filas * 2 - 1; i++) {
            for (int j = 0; j < columnas * 2 - 1; j++) {
                if (i % 2 == 0 && j % 2 == 0) { //si i y j son par entonces es espacio de boton
                    int filaBoton = i / 2;
                    int columnaBoton = j / 2;
                    
                    JButton boton = new JButton();
                    boton.setFont(new Font("Sitka Text", Font.PLAIN, Math.max(10, botonTamano / 2))); //cambia con el tamano de cuadricula
                    boton.setFocusable(false);
                    boton.setPreferredSize(new Dimension(botonTamano, botonTamano)); //para el tamano
                    boton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1)); //para los bordes documentar
                    panel.add(boton);
                    boton.setForeground(Color.RED);
                    cuadriculaBotones[filaBoton][columnaBoton] = boton;
                    
                    //comprueba constante
                    boolean esCons = false;
                    for (Map.Entry<Integer, int[]> cons : partida.getConstantes().entrySet()){
                        if (cons.getValue()[0] == filaBoton && cons.getValue()[1] == columnaBoton){
                            boton.setForeground(new Color(0,0,0));
                            boton.setText(String.valueOf(cons.getKey()));
                            cuadriculaEnJuego[filaBoton][columnaBoton] = cons.getKey();
                            System.out.println(cuadriculaToString(cuadriculaEnJuego));
                            esCons = true;
                            break;
                        }
                    }
                    
                    if (esCons == false){
                        boton.setText("");
                        boton.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                
                                if (borrarGlobal == true){
                                    boton.setText(String.valueOf(""));
                                    cuadriculaEnJuego[filaBoton][columnaBoton] = 0;
                                    
                                    int [] resultado = comprobarFilasColumnas(cuadriculaEnJuego);
                                    if (resultado!=null){
                                        alertaMensaje(errorString);
                                    }
                                    else {
                                        System.out.println("Nada");
                                        errorString = "";
                                        boton.setForeground(new Color(0,100,0)); //rgb de verde oscuro 
                                    }
                                    
                                }
                                else if (numeroElegido != 0){
                                    boton.setText(String.valueOf(numeroElegido));
                                    cuadriculaEnJuego[filaBoton][columnaBoton] = numeroElegido;
                                    
                                    System.out.println("Numero colocado en (" + filaBoton + "," + columnaBoton + "): " + numeroElegido);
                                    System.out.println("Boton presionado: " + boton.getText());
                                    System.out.println(cuadriculaToString(cuadriculaEnJuego));
                                    System.out.println(cuadriculaToString(cuadriculaJuego));

                                    int [] resultado = comprobarFilasColumnas(cuadriculaEnJuego);
                                    if (resultado!=null){
                                        alertaMensaje(errorString);
                                    }
                                    else {
                                        System.out.println("Nada");
                                        errorString = "";
                                        boton.setForeground(new Color(0,100,0)); //rgb de verde oscuro 
                                    }

                                }
                                
                                verificarDesigualdad(partida, cuadriculaEnJuego);
                                alertaFinalizar();

                            }
                        });
                    }
                    
                } else if (i % 2 == 0 || j % 2 == 0) { //si alguno no par entonces es espacio de desigualdad
                    JLabel desigualdad = new JLabel();
                    desigualdad.setFont(new Font("Sitka Text", Font.BOLD, Math.max(10, botonTamano / 3)));
                    desigualdad.setHorizontalAlignment(SwingConstants.CENTER);

                    int filaBoton = i / 2;
                    int columnaBoton = j / 2;

                    if (i % 2 == 0 && j % 2 != 0) { //desigualdad en fila maf o mef
                        for (Map.Entry<String, int[]> entry : desigualdades.entrySet()) {
                            String clave = entry.getKey();
                            int[] posicion = entry.getValue();

                            if (posicion[0] == filaBoton && posicion[1] == columnaBoton) {
                                if (clave.equals("maf")) {
                                    desigualdad.setText(">");
                                } else if (clave.equals("mef")) {
                                    desigualdad.setText("<");
                                }
                                break;
                            }
                        }
                    } else if (i % 2 != 0 && j % 2 == 0) { //desigualdad en columna mac o mec
                        for (Map.Entry<String, int[]> entry : desigualdades.entrySet()) {
                            String clave = entry.getKey();
                            int[] posicion = entry.getValue();

                            if (posicion[0] == filaBoton && posicion[1] == columnaBoton) {
                                if (clave.equals("mac")) {
                                    desigualdad.setText("v");
                                } else if (clave.equals("mec")) {
                                    desigualdad.setText("^");
                                }
                                break;
                            }
                        }
                    }

                    panel.add(desigualdad);

                } else {
                    JLabel espacio = new JLabel(); //vacio
                    panel.add(espacio);
                }
            }
        }

        panel.revalidate();
        panel.repaint();
    }
    
    /**
     * Cancela el timer
     * @param timer el timer a cancelar
     **/
    
    public void cancelarTimer(Timer timer){
        timer.cancel(); //termina el timer
    }
    
    /**
     * Construye el reloj
     **/
    
    public void construirReloj(){
        String reloj = configFutoshiki.getReloj(); //Cronometro, No, Temporizador
        
        if (reloj.equals("No")){
            relojPanel.setVisible(false);
            relojPanel.setEnabled(false);   
        }
        
        if (reloj.equals("Cronometro")){
            relojPanel.setVisible(true);
            relojPanel.setEnabled(true);  
            cronometro();
        }
        
        else if (reloj.equals("Temporizador")){
            relojPanel.setVisible(true);
            relojPanel.setEnabled(true);  
            temporizador();
        }
        
        
        
    }  
    
    /**
     * Boton de inicio de juego
     * @param evt evento
     **/
    
    private void iniciarJuegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJuegoButtonActionPerformed
        try {
            Jugador jugador = configFutoshiki.conseguirJugador(nombreJugadorField.getText());
            PartidasFutoshiki partidas = PartidasFutoshiki.cargarPartidaFutoshikiXML();
            Partida partidaJuego = partidas.partidaJugar(configFutoshiki.getNivel(), configFutoshiki.getCuadricula());
            generarCuadricula(partidaJuego, configFutoshiki.getCuadricula());
            construirReloj();
            iniciarJuegoButton.setVisible(false);
            anuncioLabel.setText("");
        }
        catch (Exception e) {
            anuncioLabel.setText("Error al encontrar juego");
        }
        
    }//GEN-LAST:event_iniciarJuegoButtonActionPerformed

    /**
     * Terminar juego boton
     * @param evt evento
     **/
    
    private void terminarJuegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarJuegoButtonActionPerformed

    }//GEN-LAST:event_terminarJuegoButtonActionPerformed

    /**
     * Boton de numero1
     * @param evt evento
     **/
    
    private void numero1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 1;
        System.out.println("1");
        numero1Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero1ButtonActionPerformed

    /**
     * Boton de numero 2
     * @param evt evento
     **/
    
    private void numero2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 2;
        System.out.println("2");
        numero2Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero2ButtonActionPerformed

    /**
     * Boton de numero 3
     * @param evt evento
     **/
    
    private void numero3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 3;
        System.out.println("3");
        numero3Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero3ButtonActionPerformed

    /**
     * Boton de numero 4
     * @param evt evento
     **/
    
    private void numero4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero4ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 4;
        numero4Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero4ButtonActionPerformed

    /**
     * Boton de numero 5
     * @param evt evento
     **/
    
    private void numero5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero5ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 5;
        numero5Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero5ButtonActionPerformed

    /**
     * Boton de numero 7
     * @param evt evento
     **/
    
    private void numero7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 7;
        numero7Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero7ButtonActionPerformed

    /**
     * Boton de numero 8
     * @param evt evento
     **/
    
    private void numero8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 8;
        numero8Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero8ButtonActionPerformed

    /**
     * Boton de numero 9
     * @param evt evento
     **/
    
    private void numero9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero9ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 9;
        numero9Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero9ButtonActionPerformed

    /**
     * Boton de numero 6
     * @param evt evento
     **/
    
    private void numero6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 6;
        numero6Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero6ButtonActionPerformed

    /**
     * Boton de numero 10
     * @param evt evento
     **/
    
    private void numero10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero10ButtonActionPerformed
        limpiarBotonesJuego();
        numeroElegido = 10;
        numero10Button.setBackground(Color.GREEN);
    }//GEN-LAST:event_numero10ButtonActionPerformed

    /**
     * Boton de borrar
     * @param evt evento
     **/
    
    private void borrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBotonActionPerformed
        if (borrarGlobal == true){
            borrarGlobal = false;
            borrarBoton.setBackground(Color.WHITE);
        }
        else {
            borrarGlobal = true;
            borrarBoton.setBackground(Color.GREEN);
        }
        
    }//GEN-LAST:event_borrarBotonActionPerformed

    /**
     * Set del nombre en el textField
     **/
    
    public static void setNombre(){
        nombreJugadorField.setText(GUIFutoshiki.getNombre());
    }
    
    /**
     * Construye el nivel
     **/
    
    public static void setNivel(){
        nivelLabel.setText(nivelLabel.getText() + " " + configFutoshiki.getNivel());
    }
    
    /**
     * Construye el temporizador
     **/
    
    public void temporizador(){
        Timer timer = new Timer();
         horaGlobal = 0;
         minutoGlobal = 0;
         segundosGlobal = 0;
        TimerTask taskCronometro = new TimerTask(){
            int hora = configFutoshiki.getTemporizadorHora();
            int minuto = configFutoshiki.getTemporizadorMinuto();
            int segundo = configFutoshiki.getTemporizadorSegundo();
            
            public void run() { //correr la tarea o task

                if (segundo > 0){
                    segundo -= 1;
                }
                
                else if (segundo == 0 ) {
                    if (minuto != 0){
                        minuto -= 1;
                    }
                    segundo = 59;
                }
                
                if (segundo == 0 && minuto == 0 && hora!=0) {
                        hora -= 1;
                        minuto = 59;
                        segundo = 59;
                }
                
                if (hora == 0 && minuto == 0 && segundo == 0){
                    timer.cancel();
                    System.out.println("Termino!");
                }
                
                
                
                SwingUtilities.invokeLater(new Runnable() { //para actualizar el GUI desde otro hilo digamos 
                public void run() {
                    tiempoHorasLabel.setText(String.valueOf(hora));
                    tiempoMinutosLabel.setText(String.valueOf(minuto));
                    tiempoSegundosLabel.setText(String.valueOf(segundo));
                    
                }
                });
            };
        };
        timer.scheduleAtFixedRate(taskCronometro, 0, 1000); //sin delay y actualizar cada 1000ms que son 1 segundo
        timerGlobal = timer;
    }
    
    /**
     * Construye el cronometro
     **/
    
    public void cronometro(){ 
        Timer timer = new Timer();
        horaGlobal = 0;
        minutoGlobal = 0;
        segundosGlobal = 0;
        TimerTask taskCronometro = new TimerTask(){
            int hora = 0;
            int minuto = 0;
            int segundo = 0;
            public void run() { //correr la tarea o task
                
                segundo += 1;
                if (segundo == 60) {
                    segundo = 0;
                    minuto += 1;
                }
                if (minuto == 60) {
                    minuto = 0;
                    hora += 1;
                }
                
                SwingUtilities.invokeLater(new Runnable() { //para actualizar el GUI desde otro hilo digamos 
                public void run() {
                    tiempoHorasLabel.setText(String.valueOf(hora));
                    tiempoMinutosLabel.setText(String.valueOf(minuto));
                    tiempoSegundosLabel.setText(String.valueOf(segundo));
                    horaGlobal = hora;
                    minutoGlobal = minuto;
                    segundosGlobal = segundo;
                }
                });
            };
        };
        timer.scheduleAtFixedRate(taskCronometro, 0, 1000); //sin delay y actualizar cada 1000ms que son 1 segundo
        timerGlobal = timer;
    }
    
    /**
     * Construye el panel de botones junto con el boton de borrar
     **/
    
    public static void construirPanel() { //para el panel de numeros
        boolean posicion = configFutoshiki.getPosicion();
        byte cuadricula = configFutoshiki.getCuadricula();
        
        int contador = 0;
        for (Component componente : numerosPanel.getComponents()) {
                if (componente instanceof JButton) {
                    JButton boton = (JButton) componente;

                    if (contador < cuadricula) {
                        boton.setVisible(true); 
                        boton.setEnabled(true);
                    } else {
                        boton.setVisible(false); //cuando supera al contador entonces oculta
                        boton.setEnabled(false); 
                    }

                    contador++;
                }
            }
        
        
        if (posicion) {
            
            fondoPanel.setLayout(null); // para que se puedan mover los componentes bien
            numerosPanel.setBounds(90, numerosPanel.getY(), numerosPanel.getWidth(), numerosPanel.getHeight());
            borrarBoton.setBounds(90, borrarBoton.getY(), borrarBoton.getWidth(), borrarBoton.getHeight());
            
            
        }
        
        fondoPanel.revalidate(); 
        fondoPanel.repaint();  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIJugar juego = new GUIJugar();
                juego.setVisible(true);
                juego.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //para que no se cierre todo al cerrar esta
                setNombre();
                setNivel();
                System.out.println(Configuracion.cargarConfiguracionXML().toStringConfiguracion());
                
                if (configFutoshiki.getReloj().equals("No")){
                    relojPanel.setVisible(false);
                    relojPanel.setEnabled(false);
                }
                juego.setBounds(0, 0, 1100, 980);
                construirPanel();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anuncioLabel;
    private static javax.swing.JButton borrarBoton;
    private javax.swing.JButton borrarJuegoButton;
    private javax.swing.JButton borrarJugadaButton;
    private javax.swing.JButton cargarJuegoButton;
    private static javax.swing.JPanel fondoPanel;
    private javax.swing.JButton guardarJuegoButton;
    private javax.swing.JLabel horasLabel;
    private javax.swing.JButton iniciarJuegoButton;
    private javax.swing.JPanel juegoPanel;
    private javax.swing.JLabel minutosLabel;
    private static javax.swing.JLabel nivelLabel;
    private static javax.swing.JTextField nombreJugadorField;
    private javax.swing.JLabel nombreJugadorLabel;
    private javax.swing.JPanel nombreJugadorPanel;
    private javax.swing.JButton numero10Button;
    private javax.swing.JButton numero1Button;
    private javax.swing.JButton numero2Button;
    private javax.swing.JButton numero3Button;
    private javax.swing.JButton numero4Button;
    private javax.swing.JButton numero5Button;
    private javax.swing.JButton numero6Button;
    private javax.swing.JButton numero7Button;
    private javax.swing.JButton numero8Button;
    private javax.swing.JButton numero9Button;
    private static javax.swing.JPanel numerosPanel;
    private javax.swing.JButton rehacerJugadaButton;
    private static javax.swing.JPanel relojPanel;
    private javax.swing.JLabel segundosLabel;
    private javax.swing.JButton terminarJuegoButton;
    private javax.swing.JLabel tiempoHorasLabel;
    private javax.swing.JLabel tiempoMinutosLabel;
    private javax.swing.JLabel tiempoSegundosLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
