
package vistaFutoshiki;

import modeloFutoshiki.Top10;
import java.util.Map;

public class GUITop10 extends javax.swing.JFrame {
    
    public static Top10 top10Actual;
    
    public GUITop10() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop10 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDificil = new javax.swing.JLabel();
        labelIntermedio = new javax.swing.JLabel();
        labelFacil = new javax.swing.JLabel();
        scrollPaneDificil = new javax.swing.JScrollPane();
        tableDificil = new javax.swing.JTable();
        scrollPaneIntermedio = new javax.swing.JScrollPane();
        tableIntermedio = new javax.swing.JTable();
        scrollPaneFacil = new javax.swing.JScrollPane();
        tableFacil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTop10.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setBackground(new java.awt.Color(204, 0, 102));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOP 10");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelDificil.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        labelDificil.setForeground(new java.awt.Color(0, 0, 0));
        labelDificil.setText("Nivel Dificil:");

        labelIntermedio.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        labelIntermedio.setForeground(new java.awt.Color(0, 0, 0));
        labelIntermedio.setText("Nivel Intermedio:");

        labelFacil.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        labelFacil.setForeground(new java.awt.Color(0, 0, 0));
        labelFacil.setText("Nivel Facil:");

        scrollPaneDificil.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneDificil.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneDificil.setToolTipText("");
        scrollPaneDificil.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableDificil.setBackground(new java.awt.Color(255, 255, 255));
        tableDificil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableDificil.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tableDificil.setForeground(new java.awt.Color(0, 0, 0));
        tableDificil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null},
                { new Integer(7), null, null},
                { new Integer(8), null, null},
                { new Integer(9), null, null},
                { new Integer(10), null, null}
            },
            new String [] {
                "", "JUGADOR", "TIEMPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDificil.setAutoscrolls(false);
        tableDificil.setFocusable(false);
        tableDificil.setRequestFocusEnabled(false);
        tableDificil.setRowSelectionAllowed(false);
        tableDificil.setShowGrid(true);
        scrollPaneDificil.setViewportView(tableDificil);

        scrollPaneIntermedio.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneIntermedio.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneIntermedio.setToolTipText("");
        scrollPaneIntermedio.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableIntermedio.setBackground(new java.awt.Color(255, 255, 255));
        tableIntermedio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableIntermedio.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tableIntermedio.setForeground(new java.awt.Color(0, 0, 0));
        tableIntermedio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null},
                { new Integer(7), null, null},
                { new Integer(8), null, null},
                { new Integer(9), null, null},
                { new Integer(10), null, null}
            },
            new String [] {
                "", "JUGADOR", "TIEMPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIntermedio.setAutoscrolls(false);
        tableIntermedio.setFocusable(false);
        tableIntermedio.setRequestFocusEnabled(false);
        tableIntermedio.setRowSelectionAllowed(false);
        tableIntermedio.setShowGrid(true);
        scrollPaneIntermedio.setViewportView(tableIntermedio);

        scrollPaneFacil.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneFacil.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneFacil.setToolTipText("");
        scrollPaneFacil.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableFacil.setBackground(new java.awt.Color(255, 255, 255));
        tableFacil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableFacil.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tableFacil.setForeground(new java.awt.Color(0, 0, 0));
        tableFacil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null},
                { new Integer(7), null, null},
                { new Integer(8), null, null},
                { new Integer(9), null, null},
                { new Integer(10), null, null}
            },
            new String [] {
                "", "JUGADOR", "TIEMPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFacil.setAutoscrolls(false);
        tableFacil.setFocusable(false);
        tableFacil.setRequestFocusEnabled(false);
        tableFacil.setRowSelectionAllowed(false);
        tableFacil.setShowGrid(true);
        scrollPaneFacil.setViewportView(tableFacil);

        javax.swing.GroupLayout panelTop10Layout = new javax.swing.GroupLayout(panelTop10);
        panelTop10.setLayout(panelTop10Layout);
        panelTop10Layout.setHorizontalGroup(
            panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTop10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDificil)
                    .addComponent(labelIntermedio)
                    .addComponent(labelFacil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTop10Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTop10Layout.createSequentialGroup()
                    .addContainerGap(131, Short.MAX_VALUE)
                    .addComponent(scrollPaneDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53)))
        );
        panelTop10Layout.setVerticalGroup(
            panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTop10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelDificil)
                .addGap(166, 166, 166)
                .addComponent(labelIntermedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTop10Layout.createSequentialGroup()
                        .addComponent(labelFacil)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTop10Layout.createSequentialGroup()
                        .addComponent(scrollPaneFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(panelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTop10Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(scrollPaneDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTop10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTop10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set del top10
     * @param top top10
     **/
    
    public static void setTop(Top10 top){
        top10Actual = top;
    }
    
    /**
     * Construye en las table de cada panel los datos del top10
     **/
    
    public static void construirTablas(){
        int contador;
        if (Top10.jugadoresFacil != null){
            contador = 0;
            for (Map.Entry<String, String> jugador : Top10.jugadoresFacil.entrySet()) {
                tableFacil.setValueAt(jugador.getKey(), contador, 1);
                tableFacil.setValueAt(jugador.getValue(), contador, 2);
                contador ++;
            }
        }
        if (Top10.jugadoresIntermedio != null){
            contador = 0;
            for (Map.Entry<String, String> jugador : Top10.jugadoresIntermedio.entrySet()) {
                tableIntermedio.setValueAt(jugador.getKey(), contador, 1);
                tableIntermedio.setValueAt(jugador.getValue(), contador, 2);
                contador ++;
            }
        }
        if (Top10.jugadoresDificil != null){
            contador = 0;
            for (Map.Entry<String, String> jugador : Top10.jugadoresDificil.entrySet()) {
                tableDificil.setValueAt(jugador.getKey(), contador, 1);
                tableDificil.setValueAt(jugador.getValue(), contador, 2);
                contador ++;
            }
        
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUITop10 guiTop = new GUITop10();
                guiTop.setVisible(true);
                try {
                    setTop(Top10.cargarTopXML());
                    construirTablas();
                    
                } catch (Exception e) {
                    System.out.println("Archivo no encontrado"); //la primera vez 
                }
                System.out.println(Top10.toStringJugadoresFacil());
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDificil;
    private javax.swing.JLabel labelFacil;
    private javax.swing.JLabel labelIntermedio;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTop10;
    private static javax.swing.JScrollPane scrollPaneDificil;
    private static javax.swing.JScrollPane scrollPaneFacil;
    private static javax.swing.JScrollPane scrollPaneIntermedio;
    private static javax.swing.JTable tableDificil;
    private static javax.swing.JTable tableFacil;
    private static javax.swing.JTable tableIntermedio;
    // End of variables declaration//GEN-END:variables
}
