
package com.mycompany.programa2futoshiki;

import javax.swing.*; //swing para el gui
import java.awt.*; //para component componentes 
import java.io.*; //manejo de archivos


import java.util.ArrayList; //DE MOMENTO NO LO USO PERO POR SI ACASO (en caso de no borrar)
import java.util.Collections;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class GUIFutoshiki extends javax.swing.JFrame {
    //variables globales 
    private static String nombre = "incognito";
    private static String password;
    /**
     * Creates new form GUIFutoshiki
     */
    public GUIFutoshiki() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fondoPanel = new javax.swing.JPanel();
        panelFutoshiki = new javax.swing.JPanel();
        labelFutoshiki = new javax.swing.JLabel();
        labelMenu = new javax.swing.JLabel();
        indicadorLabel = new javax.swing.JLabel();
        jugadorLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuConfigurar = new javax.swing.JMenu();
        menuTamanoCuadricula = new javax.swing.JMenu();
        item3x3 = new javax.swing.JMenuItem();
        item4x4 = new javax.swing.JMenuItem();
        item5x5 = new javax.swing.JMenuItem();
        item6x6 = new javax.swing.JMenuItem();
        item7x7 = new javax.swing.JMenuItem();
        item8x8 = new javax.swing.JMenuItem();
        item9x9 = new javax.swing.JMenuItem();
        item10x10 = new javax.swing.JMenuItem();
        menuNivel = new javax.swing.JMenu();
        nivelFacil = new javax.swing.JMenuItem();
        nivelIntermedio = new javax.swing.JMenuItem();
        nivelDificil = new javax.swing.JMenuItem();
        menuMultinivel = new javax.swing.JMenu();
        itemNoMultinivel = new javax.swing.JMenuItem();
        itemSiMultinivel = new javax.swing.JMenuItem();
        menuReloj = new javax.swing.JMenu();
        itemRelojCronometro = new javax.swing.JMenuItem();
        itemRelojNo = new javax.swing.JMenuItem();
        itemRelojTemporizador = new javax.swing.JMenuItem();
        menuPanelDigitos = new javax.swing.JMenu();
        itemPosicionDerecha = new javax.swing.JMenuItem();
        itemPosicionIzquierda = new javax.swing.JMenuItem();
        itemNombreJugador = new javax.swing.JMenuItem();
        menuJugar = new javax.swing.JMenu();
        menuTop10 = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelFutoshiki.setBackground(new java.awt.Color(204, 0, 51));

        labelFutoshiki.setBackground(new java.awt.Color(204, 0, 51));
        labelFutoshiki.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        labelFutoshiki.setForeground(new java.awt.Color(255, 255, 255));
        labelFutoshiki.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFutoshiki.setText("FUTOSHIKI");
        labelFutoshiki.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelFutoshikiLayout = new javax.swing.GroupLayout(panelFutoshiki);
        panelFutoshiki.setLayout(panelFutoshikiLayout);
        panelFutoshikiLayout.setHorizontalGroup(
            panelFutoshikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFutoshikiLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(labelFutoshiki, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFutoshikiLayout.setVerticalGroup(
            panelFutoshikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFutoshikiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFutoshiki, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelMenu.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(0, 0, 0));
        labelMenu.setText("Menu Principal");

        indicadorLabel.setForeground(new java.awt.Color(0, 0, 0));

        jugadorLabel.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jugadorLabel.setForeground(new java.awt.Color(0, 0, 0));
        jugadorLabel.setText("Jugador: ");

        javax.swing.GroupLayout fondoPanelLayout = new javax.swing.GroupLayout(fondoPanel);
        fondoPanel.setLayout(fondoPanelLayout);
        fondoPanelLayout.setHorizontalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoPanelLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(indicadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoPanelLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(labelMenu))
                    .addGroup(fondoPanelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelFutoshiki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoPanelLayout.setVerticalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(panelFutoshiki, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMenu)
                .addGap(18, 18, 18)
                .addComponent(indicadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        menuBar.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N

        menuConfigurar.setText("Configurar");

        menuTamanoCuadricula.setText("Tamaño de la Cuadricula");

        item3x3.setText("3 x 3");
        menuTamanoCuadricula.add(item3x3);

        item4x4.setText("4 x 4");
        menuTamanoCuadricula.add(item4x4);

        item5x5.setForeground(new java.awt.Color(255, 0, 51));
        item5x5.setText("5 x 5");
        menuTamanoCuadricula.add(item5x5);

        item6x6.setText("6 x 6");
        menuTamanoCuadricula.add(item6x6);

        item7x7.setText("7 x 7");
        menuTamanoCuadricula.add(item7x7);

        item8x8.setText("8 x 8");
        menuTamanoCuadricula.add(item8x8);

        item9x9.setText("9 x 9");
        menuTamanoCuadricula.add(item9x9);

        item10x10.setText("10 x 10");
        menuTamanoCuadricula.add(item10x10);

        menuConfigurar.add(menuTamanoCuadricula);

        menuNivel.setText("Nivel de Juego");

        nivelFacil.setForeground(new java.awt.Color(255, 0, 0));
        nivelFacil.setText("Facil");
        menuNivel.add(nivelFacil);

        nivelIntermedio.setText("Intermedio");
        menuNivel.add(nivelIntermedio);

        nivelDificil.setText("Dificil");
        menuNivel.add(nivelDificil);

        menuConfigurar.add(menuNivel);

        menuMultinivel.setText("Multinivel");

        itemNoMultinivel.setForeground(new java.awt.Color(255, 0, 0));
        itemNoMultinivel.setText("No");
        menuMultinivel.add(itemNoMultinivel);

        itemSiMultinivel.setText("Si");
        menuMultinivel.add(itemSiMultinivel);

        menuConfigurar.add(menuMultinivel);

        menuReloj.setText("Uso del reloj");

        itemRelojCronometro.setForeground(new java.awt.Color(255, 0, 0));
        itemRelojCronometro.setText("Cronometro");
        menuReloj.add(itemRelojCronometro);

        itemRelojNo.setText("No");
        menuReloj.add(itemRelojNo);

        itemRelojTemporizador.setText("Temporizador");
        menuReloj.add(itemRelojTemporizador);

        menuConfigurar.add(menuReloj);

        menuPanelDigitos.setText("Posición en la ventana del panel de dígitos");

        itemPosicionDerecha.setForeground(new java.awt.Color(255, 0, 0));
        itemPosicionDerecha.setText("Derecha");
        menuPanelDigitos.add(itemPosicionDerecha);

        itemPosicionIzquierda.setText("Izquierda");
        menuPanelDigitos.add(itemPosicionIzquierda);

        menuConfigurar.add(menuPanelDigitos);

        itemNombreJugador.setText("Nombre del jugador");
        itemNombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNombreJugadorActionPerformed(evt);
            }
        });
        menuConfigurar.add(itemNombreJugador);

        menuBar.add(menuConfigurar);

        menuJugar.setText("Jugar");
        menuBar.add(menuJugar);

        menuTop10.setText("Top 10");
        menuBar.add(menuTop10);

        menuAyuda.setText("Ayuda");
        menuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAyudaMouseClicked(evt);
            }
        });
        menuBar.add(menuAyuda);

        menuAcercaDe.setText("Acerca de.");
        menuAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcercaDeMouseClicked(evt);
            }
        });
        menuBar.add(menuAcercaDe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void setNombre(String pNombre){
        nombre = pNombre;
    }
    
    public static void setPassword(String pPassword){
        password = pPassword;
    }
    
    public static void setJugadorLabel(){
        jugadorLabel.setText("Jugador: "+nombre);
    }
    
    public static String getNombre(){
        return nombre;
    }
    
    public static String getPassword(){
        return password;
    }
    
    private void menuAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcercaDeMouseClicked
         System.out.println("Acerca de.");
        
         //informacion 
         JTextArea areaTexto = new JTextArea();
         areaTexto.setEditable(false);
         areaTexto.setText("FUTOSHIKI \n"
                          +"Version: PONER AL TERMINAR \n"
                          +"Fecha de creación: 24/10/2024 \n"
                          +"Autor: Kendall Ariel Rojas Cartin");
         areaTexto.setFont(new Font("Sitka Text",Font.BOLD,22));
         
        //ventana para mostrar la informacion
        JDialog ventanaInfo = new JDialog();
        ventanaInfo.setTitle("Acerca De.");
        ventanaInfo.setModal(true); // lo pone en modal lo que hace que no se pueda hacer nada hasta cerrar 
        ventanaInfo.setBounds(500, 500, 500, 300); // x y ancho y altura
        
        ventanaInfo.add(areaTexto);
        ventanaInfo.setVisible(true);
        
        
    }//GEN-LAST:event_menuAcercaDeMouseClicked

    private void menuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAyudaMouseClicked
        System.out.println("PDF");
        try {
            File archivoPDF = new File("files/programa2_futoshiki_manual_de_usuario.pdf"); //RECORDAR QUE EL MANUAL ESTA VACIO (Borrar comentario luego)

            if (archivoPDF.exists()){ //determina si existe
                Desktop.getDesktop().open(archivoPDF); //Desktop es para acceder a las funciones y de esta manera abrir el archivo
            } else {
                indicadorLabel.setText("No se encontro el PDF");
            }
        } 
        catch (IOException e) { //si hay un error al abrir
            indicadorLabel.setText(e.getMessage());
        }
    }//GEN-LAST:event_menuAyudaMouseClicked

    private void itemNombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNombreJugadorActionPerformed
        System.out.println("Nombre");
        
        GUIJugador nuevoInicio = new GUIJugador();
        nuevoInicio.setVisible(true);
        nuevoInicio.setEnabled(true);
        nuevoInicio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //para que no se cierre todo al cerrar esta
    }//GEN-LAST:event_itemNombreJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFutoshiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFutoshiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFutoshiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFutoshiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFutoshiki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel indicadorLabel;
    private javax.swing.JMenuItem item10x10;
    private javax.swing.JMenuItem item3x3;
    private javax.swing.JMenuItem item4x4;
    private javax.swing.JMenuItem item5x5;
    private javax.swing.JMenuItem item6x6;
    private javax.swing.JMenuItem item7x7;
    private javax.swing.JMenuItem item8x8;
    private javax.swing.JMenuItem item9x9;
    private javax.swing.JMenuItem itemNoMultinivel;
    private javax.swing.JMenuItem itemNombreJugador;
    private javax.swing.JMenuItem itemPosicionDerecha;
    private javax.swing.JMenuItem itemPosicionIzquierda;
    private javax.swing.JMenuItem itemRelojCronometro;
    private javax.swing.JMenuItem itemRelojNo;
    private javax.swing.JMenuItem itemRelojTemporizador;
    private javax.swing.JMenuItem itemSiMultinivel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private static javax.swing.JLabel jugadorLabel;
    private javax.swing.JLabel labelFutoshiki;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConfigurar;
    private javax.swing.JMenu menuJugar;
    private javax.swing.JMenu menuMultinivel;
    private javax.swing.JMenu menuNivel;
    private javax.swing.JMenu menuPanelDigitos;
    private javax.swing.JMenu menuReloj;
    private javax.swing.JMenu menuTamanoCuadricula;
    private javax.swing.JMenu menuTop10;
    private javax.swing.JMenuItem nivelDificil;
    private javax.swing.JMenuItem nivelFacil;
    private javax.swing.JMenuItem nivelIntermedio;
    private javax.swing.JPanel panelFutoshiki;
    // End of variables declaration//GEN-END:variables
}
