/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programa2futoshiki;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Usuario
 */
public class GUIJugador extends javax.swing.JFrame {
    

    
    /**
     * Creates new form GUIJugador
     */
    public GUIJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        registroButton = new javax.swing.JButton();
        nombreField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        sesionLabel = new javax.swing.JLabel();
        iniciarButton = new javax.swing.JButton();
        indicadorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        fondoPanel.setForeground(new java.awt.Color(0, 0, 0));

        tituloLabel.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setText("Jugador");

        registroButton.setBackground(new java.awt.Color(255, 153, 153));
        registroButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        registroButton.setForeground(new java.awt.Color(255, 255, 255));
        registroButton.setText("Registrarse");
        registroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroButtonActionPerformed(evt);
            }
        });

        nombreField.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        sesionLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        sesionLabel.setForeground(new java.awt.Color(0, 0, 0));
        sesionLabel.setText("Inicio Sesion");

        iniciarButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        iniciarButton.setText("Iniciar");
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        indicadorLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout fondoPanelLayout = new javax.swing.GroupLayout(fondoPanel);
        fondoPanel.setLayout(fondoPanelLayout);
        fondoPanelLayout.setHorizontalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(tituloLabel)
                        .addGap(30, 30, 30)
                        .addComponent(sesionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(fondoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(passwordField))
                        .addGap(26, 26, 26)
                        .addComponent(iniciarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registroButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(indicadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fondoPanelLayout.setVerticalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tituloLabel))
                    .addGroup(fondoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sesionLabel)))
                .addGap(24, 24, 24)
                .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroButton)
                    .addComponent(indicadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        indicadorLabel.setText("");
        if (nombreField.getText().isEmpty() && passwordField.getText().isEmpty()){
            GUIFutoshiki.setNombre("incognito");
            GUIFutoshiki.setJugadorLabel();
            System.out.println(GUIFutoshiki.getNombre());
            System.out.println(GUIFutoshiki.getPassword());
            this.setEnabled(false);
            this.setVisible(false);
        }
        else if(Configuracion.nombreValido(nombreField.getText())){
            try {
            if (Configuracion.jugadores.get(nombreField.getText()).equals(passwordField.getText())){
                GUIFutoshiki.setNombre(nombreField.getText());
                GUIFutoshiki.setPassword(passwordField.getText());
                GUIFutoshiki.setJugadorLabel();
                System.out.println(GUIFutoshiki.getNombre());
                System.out.println(GUIFutoshiki.getPassword());
                this.setEnabled(false);
                this.setVisible(false);
            }
            else {
                indicadorLabel.setText("Usuario o contrasena invalidos");
            }
            }
            catch (NullPointerException e){
                indicadorLabel.setText("Error al buscar usuario");
            }
        }

        
    }//GEN-LAST:event_iniciarButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void registroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroButtonActionPerformed

    private Component buscarComponente(String nombre){ //Busca un boton con el texto que este posee
        Component[] listaComponentes = fondoPanel.getComponents(); //consigue los componentes del JPanel fondoPabel
            for (Component i : listaComponentes) {
                if (i.getName().equals(nombre)){
                    i.setVisible(true);
                    i.setEnabled(true);
                    return i;
                }
            }
        return null;
    }
      /*  
    public String getNombre(){
        return nombre;
    }
    public String getPassword(){
        return password;*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel indicadorLabel;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton registroButton;
    private javax.swing.JLabel sesionLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
